#!/bin/sh

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

rotate() {
	degree="$1"
	tr '\n' '\0' | xargs -0 realpath | sort | uniq | while read file; do
		case "$(file -b -i "$file")" in
		image/jpeg*) jpegtran -rotate "$degree" -copy all -outfile "$file" "$file" ;;
		*)           mogrify  -rotate "$degree" "$file" ;;
		esac
	done
}

case "$1" in
"C-x")      xclip -in -filter | tr '\n' ' ' | xclip -in -selection clipboard ;;
"y")      while read file; do xclip -selection clipboard -target image/png "$file"; done ;;
"C-e")      while read file; do urxvt -bg "#444" -fg "#eee" -sl 0 -title "$file" -e sh -c "exiv2 pr -q -pa '$file' | less" & done ;;
"C-g")      tr '\n' '\0' | xargs -0 gimp & ;;
"C-w")
    while read -r file; do
        TARGET="$HOME/.dotfiles/i3/Wallpaper/Wallpaper"
        rm -f "$TARGET"
        ln -s "$file" "$TARGET"
        sxiv -B "$file"
        notify-send "Wallpaper Changed" "Set to $file"
    done
    ;;
"c")
    #!/bin/bash

    while read -r file; do
        dir="$(dirname "$file")"
        base="$(basename "$file")"
        name="${base%.*}"
        ext="${base##*.}"

        case "$1" in
            c)
                # Launch sxiv fullscreen in a separate window if not already
                # Using -f for fullscreen and -a for auto-zoom to 100%
                sxiv -f -a "$file" &

            # Give sxiv a moment to render
            sleep 0.2

            # Select region interactively
            eval $(slop -f "X=%x Y=%y W=%w H=%h")

            # Crop the image
            magick "$file" -crop ${W}x${H}+${X}+${Y} +repage \
                "$dir/${name}_cropped.$ext"

            # Kill the fullscreen sxiv after cropping
            pkill -f "sxiv -f -a $file"
            ;;
    esac
done
esac

