#!/bin/sh

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

rotate() {
	degree="$1"
	tr '\n' '\0' | xargs -0 realpath | sort | uniq | while read file; do
		case "$(file -b -i "$file")" in
		image/jpeg*) jpegtran -rotate "$degree" -copy all -outfile "$file" "$file" ;;
		*)           mogrify  -rotate "$degree" "$file" ;;
		esac
	done
}

changedir() {

CACHE="$HOME/.cache/sxiv/dirs"
mkdir -p "$(dirname "$CACHE")"
touch "$CACHE"

SELECTED=$(tac "$CACHE" | awk '!seen[$0]++' | rofi -dmenu -p "sxiv cd")

[ -z "$SELECTED" ] && exit

echo "$SELECTED" >> "$CACHE"

# Remove duplicates, keep newest priority
tac "$CACHE" | awk '!seen[$0]++' | tac > "$CACHE.tmp"
mv "$CACHE.tmp" "$CACHE"

# Launch new sxiv in background
sxiv "$SELECTED"

}

case "$1" in
"C-x")      xclip -in -filter | tr '\n' ' ' | xclip -in -selection clipboard ;;
"C-c")      while read file; do xclip -selection clipboard -target image/png "$file"; done ;;
"C-e")      while read file; do urxvt -bg "#444" -fg "#eee" -sl 0 -title "$file" -e sh -c "exiv2 pr -q -pa '$file' | less" & done ;;
"C-g")      tr '\n' '\0' | xargs -0 gimp & ;;
"i")      
    while read file; do
        qimgv "$file" & 
        exit
    done ;;
"C-w")
    while read -r file; do
        TARGET="$HOME/.dotfiles/i3/Wallpaper/Wallpaper"
        rm -f "$TARGET"
        ln -s "$file" "$TARGET"
        feh --bg-fill "$file"
        notify-send "Wallpaper Changed" "Set to $file"
    done
    ;;
"c")      changedir ;;
esac

